// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: messaging.proto

package io.grpc.examples.messaging;

public final class Messages {
  private Messages() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_messaging_MessageRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_messaging_MessageRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_messaging_MessageResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_messaging_MessageResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017messaging.proto\022\tmessaging\"E\n\016MessageR" +
      "equest\022\022\n\nmessage_id\030\001 \001(\t\022\021\n\tsender_id\030" +
      "\002 \001(\t\022\014\n\004text\030\003 \001(\t\"6\n\017MessageResponse\022\023" +
      "\n\013response_id\030\001 \001(\t\022\016\n\006status\030\002 \001(\t2\242\001\n\t" +
      "Messaging\022D\n\013SendMessage\022\031.messaging.Mes" +
      "sageRequest\032\032.messaging.MessageResponse\022" +
      "O\n\022SendReceiveMessage\022\031.messaging.Messag" +
      "eRequest\032\032.messaging.MessageResponse(\0010\001" +
      "B.\n\032io.grpc.examples.messagingB\010Messages" +
      "P\001\242\002\003MSGb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_messaging_MessageRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_messaging_MessageRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_messaging_MessageRequest_descriptor,
        new java.lang.String[] { "MessageId", "SenderId", "Text", });
    internal_static_messaging_MessageResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_messaging_MessageResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_messaging_MessageResponse_descriptor,
        new java.lang.String[] { "ResponseId", "Status", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
