// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: messaging.proto

package io.grpc.examples.messaging;

public interface MessageResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:messaging.MessageResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string response_id = 1;</code>
   */
  java.lang.String getResponseId();
  /**
   * <code>string response_id = 1;</code>
   */
  com.google.protobuf.ByteString
      getResponseIdBytes();

  /**
   * <code>string status = 2;</code>
   */
  java.lang.String getStatus();
  /**
   * <code>string status = 2;</code>
   */
  com.google.protobuf.ByteString
      getStatusBytes();
}
