// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: messaging.proto

package io.grpc.examples.messaging;

public interface MessageRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:messaging.MessageRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string message_id = 1;</code>
   */
  java.lang.String getMessageId();
  /**
   * <code>string message_id = 1;</code>
   */
  com.google.protobuf.ByteString
      getMessageIdBytes();

  /**
   * <code>string sender_id = 2;</code>
   */
  java.lang.String getSenderId();
  /**
   * <code>string sender_id = 2;</code>
   */
  com.google.protobuf.ByteString
      getSenderIdBytes();

  /**
   * <code>string text = 3;</code>
   */
  java.lang.String getText();
  /**
   * <code>string text = 3;</code>
   */
  com.google.protobuf.ByteString
      getTextBytes();
}
